version: "3.8"
# Define app infrastructure

# volumes: 
#   dbvol: # database
#   hive: # shared volume between queenBee and busyBee
#   public: # SAMBA share for IO of data
    # driver_opts: 
    #   type: "cifs"
    #   device: "//127.0.0.1/public"
    #   o: "username=${SAMBA_UNAME},password=${SAMBA_PW}"

services:
# backend
  # API - interfaces with db and dispatches jobs to worker containers
  queenbee:
    container_name: queenBee_container
    image: queenbee
    ports:
      - "3000:3000"
    links: 
      - database
    depends_on:
      - database
    volumes: 
      - type: volume
        source: hive
        target: /app/workspace
      # - /var/run/docker.sock:/var/run/docker.sock # Must set perms on host
      # - "./public:/srv/public" # Must mount CIFS because contents of volume are owned by ROOT
    environment:
      - NODE_ENV=production
    # privileged: true # TODO: test removal or replacement with capabilities
    # command: ["npm", "start"]

  # Persistent DB
  database:
    container_name: db_container
    image: mongo 
    # ports:
    #   - "27017:27017"
    volumes:
      - type: volume
        source: dbvol
        target: /data/db
    # command: ["mongod", "--bind_ip", "localhost,database"]

# front end
  # Nextjs Client App 
  beekeeper:
    container_name: beekeeper_container
    image: beekeeper
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    links:
      - "queenbee"
    depends_on:
      - "queenbee"
    # command: ["npm", "start"]